### ISSUE TITLE
QR code on badges should use better vCard format

### ISSUE THREAD

**Issue by malemburg** [EuroPython/ep-tools#8]
The vCard format on the QR codes looked like this for 2016:
```
BEGIN:VCARD
VERSION:3.0
N:Marc-Andre;Lemburg
FN:Marc-Andre Lemburg
EMAIL:mal@example.net
ORG:Title @ Company
URL:www.example.com/
NOTE:+PhoneNumber
END:VCARD
```

As a result, QR readers would not create correct contact entries. For 2017, we should have more compatible formats (see https://tools.ietf.org/html/rfc6350):

```
BEGIN:VCARD
VERSION:3.0
N:Lemburg;Marc-Andre;;;
FN:Marc-Andre Lemburg
EMAIL:mal@example.net
ORG:Company
TITLE:Title
URL:http://www.example.com/
NOTE:EuroPython 2017
END:VCARD
```

Some things to correct:
* N: field uses wrong order and misses empty entries
* ORG: field should only have the company
* TITLE: field is meant for title
* URL: fields needs to be a valid URL (with scheme)
* NOTE: would be good to list where this contact originated

Please remove the phone number from the record altogether - this information should not accidentally be disclosed (eg. via posting a photo on Twitter).

**Comment by malemburg** [comment]
The profile also has a location field we could add as address label:
```
ADR;LABEL="{{ contact.location }}":;;;;;;
```

**Comment by alexsavio** [comment]
Thanks Marc. I think I can address most of the issues.

**Comment by alexsavio** [comment]
One of my main concerns last year is that the size of the QR didn't allow me to put much stuff. Otherwise the QR pattern is too smal for standard cameras.

**Comment by europython-society** [comment]
On 25.04.2017 23:21, Alexandre M. S. wrote:
> One of my main concerns last year is that the size of the QR didn't allow me to put much stuff. Otherwise the QR pattern is too smal for standard cameras.

I think you can address this by using a higher contrast. Last
year the contract was rather low. Some dark color on white should
work better.

Also note that cameras got better and companies wanting to scan
the QR codes will most likely have good ones :-)

-- 
Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by alexsavio** [comment]
Ooops, this is an issue for docstamp, not ep-tools. :)
I will solve this, there.

**Comment by alexsavio** [comment]
I've solved the issue on docstamp and in ep-tools. One thing left to do is to change this year's template to have one line for `{{ company }}` and another for `{{ title }}`.
